version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
    - funcorder
    - asciicheck
    - bidichk
    - contextcheck
    - copyloopvar
    - godot
    - gosec
    - nolintlint
    - errname
    - errorlint
    - nilerr
    - gocritic
    - bodyclose
    - exhaustive
    - usestdlibvars
    - wastedassign
    - reassign
    - thelper
    - containedctx
    - decorder
    - dogsled
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - errchkjson
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - gocheckcompilerdirectives
    - gochecksumtype
    - godoclint
    - godox
    - gomoddirectives
    - gosmopolitan
    - grouper
    - iface
    - importas
    - intrange
    - iotamixing
    - ireturn
    - loggercheck
    - makezero
    - mirror
    - mnd
    - musttag
    - nakedret
    - noctx
    - nosprintfhostport
    - perfsprint
    - predeclared
    - promlinter
    - reassign
    - recvcheck
    - rowserrcheck
    - sloglint
    - sqlclosecheck
    - tagalign
    - unqueryvet
    - unused
    - usetesting
    - whitespace
    - wrapcheck
    - wsl_v5
  settings:
    revive:
      enable-default-rules: true
      rules:
        - name: exported
          severity: warning
          disabled: false
          arguments:
            - "disable-checks-on-constants"
        - name: dot-imports
          severity: warning
          disabled: false
          exclude: [ "" ]
          arguments:
            - allowed-packages:
              - "github.com/onsi/ginkgo/v2"
              - "github.com/onsi/gomega"
        - name: package-comments
          disabled: true
    gosec:
      excludes:
        - G204
    godot:
      exclude:
        - "^ *\\+operator-sdk:"
    ireturn:
      allow:
        - error
        - empty
        - stdlib
        - generic
        - Option$
        - github.com\/ClickHouse\/clickhouse-go/v2\.Conn
        - k8s.io
    wsl_v5:
      allow-whole-block: true
      branch-max-lines: 4
      case-max-lines: 4
    mnd:
      ignored-numbers: [ '2' ]
      ignored-files:
        - test/.*\.go
        - internal/controller/testutil/.*\.go
  exclusions:
    generated: lax
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      # Put imports beginning with prefix after 3rd-party packages.
      local-prefixes:
       - github.com/ClickHouse/clickhouse-operator
    gofmt:
      simplify: true
      rewrite-rules:
        -   pattern: 'interface{}'
            replacement: 'any'
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
