name: Documentation Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
permissions:
  contents: read
  statuses: write
  checks: write
  pull-requests: write

jobs:
  vale:
    name: vale-linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: errata-ai/vale-action@2.1.2
        with:
          fail_on_error: 'true'
          filter_mode: nofilter

  doc-links:
    name: Doc links
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: dorny/paths-filter@v4
        id: changes
        with:
          filters: |
            docs:
              - 'docs/**'
      - if: steps.changes.outputs.docs == 'true'
        uses: UmbrellaDocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: nofilter
          fail_level: any
          config_file: .linkspector.yml

  api-reference-generated:
    name: API Reference Generated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'

      - name: Generate API Reference
        run: make docs-generate-api-ref

      - name: Check API Reference generated
        run: git diff --exit-code docs/

  ci-success-check:
    name: All Docs CI checks passed
    runs-on: ubuntu-latest
    needs: [ vale, doc-links, api-reference-generated ]
    if: always()
    steps:
      - name: Determine CI status
        id: status
        run: |
          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
            echo "One or more CI jobs failed or were cancelled"
            exit 1
          else
            echo "All required jobs passed successfully"
          fi
