name: Publish main branch artifact
on:
  push:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_REPO: ghcr.io/clickhouse

jobs:
  release-main:
    permissions:
      packages: write
      attestations: write
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-tags: true
          fetch-depth: '0'
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.0
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install jq
        uses: dcarbone/install-jq-action@v3.2.0
      - name: Build operator image
        run: make docker-buildx-latest
      - name: Install Helm
        run: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - name: Set VERSION
        run: |
          FULL_VER=$(make -s print-full-version)
          echo "VERSION=${FULL_VER#v}" >> "$GITHUB_ENV"
      - name: Package and push helm charts
        run: |
          helm registry login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          make push-helmchart push-cluster-chart
      - name: Build and push fast bundle
        run: make bundle bundle-buildx
      - name: Build catalog
        run: make catalog-buildx
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Mark catalog as latest
        run: make catalog-push-latest
